spring:
  application:
    name: order-service-ribbon

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

product-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
