spring:
  application:
    name: zuul-filters

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    product:
      path: /product/**
      serviceId: product-service

management:
  endpoints:
    web:
      exposure:
        include: '*'