server:
  port: 8001

spring:
  application:
    name: hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
turbine:
  app-config: order-service-ribbon-hystrix,order-service-feign-hystrix
  cluster-name-expression: "'default'"
  combine-host-port: true