spring:
  application:
    name: order-service-ribbon

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    product:
      path: /product/**
      serviceId: product-service